# Generated by Django 2.1.1 on 2018-11-16 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdetail',
            options={},
        ),
    ]
